<main>
    <h3>Commande numéro : <?= $cdeCliquee; ?></h3>    
    <table>
        <tr>
            <th>Produit</th><th>Prix unitaire</th><th>Quantité</th><th>Total</th>
        </tr>

        <?php             
            $total = 0;
            foreach ($detailCde as $key => $value): 
            $total+=$value['total'];
        ?>  

        <tr>
            <td><?= $value['productName']; ?></td>               
            <td><?= $value['priceEach']; ?></td>
            <td><?= $value['quantityOrdered']; ?></td>
            <td><?= $value['total']; ?></td>
        </tr>

        <?php endforeach; ?>
        
        <tr>
            <th colspan="3" class="montant">Montant HT</th>
            <th><?=$total;?></th>
        </tr>

        <tr>
            <th colspan="3" class="montant">Montant TVA</th>
            <th><?=$total*0.2;?></th>
        </tr>

        <tr>
            <th colspan="3" class="montant">Montant TTC</th>
            <th><?=$total+$total*0.2?></th>
        </tr>        
    </table> 
        

    <article>
        <table id="client_tb">
            <?php
                foreach($detailClient as $key => $value):
            ?>

            <tr>
                <th>Nom et Prénom du Client</th>
                <td><?= $value['contactLastName']. ' ' .$value['contactFirstName'];?></td>                
            </tr>

            <tr>
                <th>Adresse</th>            
                <td><?= $value['addressLine1'];?></td>
            </tr>

            <tr>            
                <th>Code Postal</th>
                <td><?= $value['postalCode'];?></td>
            </tr>
            <tr>
                <th>Ville</th>
                <td><?= $value['city'];?></td>
            </tr>
            <tr>
                <th>Pays</th>
                <td><?= $value['country'];?></td>
            </tr>
            <tr>
                <th>Téléphone</th>
                <td><?= $value['phone'];?></td>
            </tr>

            <?php endforeach ?>

        </table>
    </article>
    <br>

</main>